name: "💥 Destroy Environment Infrastructure"

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      environment:
        #checkov:skip=CKV_GHA_7:user is unable to provide own input, predefined choices provided in workflow.
        type: choice
        description: Environment to destory
        required: true
        options:
          - development
          - staging
          - production

env:
  tf_version: "1.5.7"
  tg_version: "0.50.8"
  working_dir: "environments/${{ github.event.inputs.environment }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v1.0.8
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: "hclfmt --terragrunt-check --terragrunt-diff"

  destroy:
    runs-on: ubuntu-latest
    needs: [checks]
    environment: "${{ github.event.inputs.environment }}"
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v1.0.8
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: "run-all destroy"
